# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chinese_permalink}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2011-09-03}
  s.description = %q{This plugin adds a capability for AR model to create a seo permalink with your chinese text. It will translate your chinese text to english url based on google translate.}
  s.email = %q{flyerhzm@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".autotest",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "chinese_permalink.gemspec",
     "generators/chinese_permalink_migration/chinese_permalink_migration_generator.rb",
     "generators/chinese_permalink_migration/templates/migration.rb",
     "init.rb",
     "lib/chinese_permalink.rb",
     "rails/init.rb",
     "test/chines_permalink_test.rb"
  ]
  s.homepage = %q{http://github.com/flyerhzm/chinese_permalink}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{This plugin adds a capability for AR model to create a seo permalink with your chinese text.}
  s.test_files = [
    "test/chines_permalink_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

